version: '3'

services:
  django:
    build:
      context: .    # Dockerfileがあるディレクトリまでの相対パス
      dockerfile: Dockerfile   # Dockerfileのファイル名

    container_name: django

    ports:
      - "8000:8000"
    
    tty: true

    volumes:
      - ./src/tootooroo:/root/workspace/src/tootooroo  # ローカルの作業ディレクトリと仮想環境の作業ディレクトリの対応づけ

    environment:
      - DEBUG=True
      - COMPOSE_HTTP_TIMEOUT=200
      - COMPOSE_LOG_LEVEL=DEBUG

    command: ["python", "src/tootooroo/manage.py", "runserver", "0.0.0.0:8000"]

# ヘルパーサービスを追加
  makemigrations:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_makemigrations
    command: ["python", "src/tootooroo/manage.py", "makemigrations"]
    volumes:
      - ./src/tootooroo:/root/workspace/src/tootooroo

  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_migrate
    command: ["python", "src/tootooroo/manage.py", "migrate"]
    volumes:
      - ./src/tootooroo:/root/workspace/src/tootooroo

  createsuperuser:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_createsuperuser
    command: ["python", "src/tootooroo/manage.py", "createsuperuser"]
    volumes:
      - ./src/tootooroo:/root/workspace/src/tootooroo
