# Generated by Django 5.0.6 on 2024-07-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toot',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
