# Generated by Django 5.0.6 on 2024-07-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_hashtag_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='retoot',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('follower', 'following'), name='unique_follow'),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('toot', 'user'), name='unique_like'),
        ),
        migrations.AddConstraint(
            model_name='retoot',
            constraint=models.UniqueConstraint(fields=('toot', 'user'), name='unique_retoot'),
        ),
    ]
