# Generated by Django 5.0.6 on 2024-07-10 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_follow_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='background_color',
            field=models.CharField(default='#343a40', max_length=7),
        ),
    ]
