# Generated by Django 5.0.6 on 2024-07-11 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_customuser_background_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='display_name',
            field=models.CharField(default='',  max_length=150, unique=True, verbose_name='表示名'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='background_color',
            field=models.CharField(choices=[('#343a40', 'ダークカラー'), ('#f8f9fa', 'ライトカラー'), ('#007bff', 'ブルー'), ('#28a745', 'グリーン'), ('#dc3545', 'レッド')], default='#343a40', max_length=7, verbose_name='背景色'),
        ),
    ]
