# Generated by Django 5.0.6 on 2024-07-11 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_customuser_display_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='display_name',
            field=models.CharField(default='', max_length=150, unique=True, verbose_name='表示名'),
        ),
    ]
