# Generated by Django 5.0.6 on 2024-07-11 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_customuser_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='表示名'),
        ),
    ]
