# Generated by Django 5.0.6 on 2024-07-15 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_department_alter_customuser_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('toot', 'トゥート'), ('reply', 'リプライ'), ('like', 'いいね'), ('mention', 'メンション')], max_length=10, verbose_name='通知タイプ')),
                ('message', models.CharField(max_length=255, verbose_name='メッセージ')),
                ('is_read', models.BooleanField(default=False, verbose_name='既読')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to='main.customuser', verbose_name='通知送信者')),
                ('toot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='main.toot', verbose_name='関連トゥート')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='main.customuser', verbose_name='通知受信者')),
            ],
        ),
    ]
