# Generated by Django 5.0.6 on 2024-07-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(default='', max_length=255, verbose_name='メッセージ'),
        ),
    ]
