# Generated by Django 5.0.6 on 2024-07-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_notification_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('toot', 'トゥート'), ('reply', 'リプライ'), ('like', 'いいね'), ('mention', 'メンション'), ('follow', 'フォロー')], max_length=10, verbose_name='通知タイプ'),
        ),
    ]
