# Generated by Django 5.0.6 on 2024-07-16 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_notification_read_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='background_color',
            field=models.CharField(choices=[('bg-dark', 'ダークカラー'), ('bg-light', 'ライトカラー'), ('bg-blue', 'ブルー'), ('bg-green', 'グリーン'), ('bg-red', 'レッド')], default='bg-dark', max_length=20, verbose_name='背景色'),
        ),
    ]
