# Generated by Django 5.0.6 on 2024-07-16 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_customuser_background_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='background_color',
            field=models.CharField(choices=[('bg-dark', 'ダークカラー'), ('bg-blue', 'ブルー'), ('bg-green', 'グリーン'), ('bg-red', 'レッド'), ('bg-orange', 'オレンジ'), ('bg-purple', 'パープル'), ('bg-gray', 'グレー')], default='bg-dark', max_length=20, verbose_name='背景色'),
        ),
    ]
